[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth

phone_number="+44 7441 344278"
api_id=29359388
api_hash="0c026853a208c8c7b0ac8466cf488988"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=0
loop_interval=5
