[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth

phone_number="+1 5153859073"
api_id=24063630

api_hash="8b4026aa9b69c31c860c395f99bf7a5d"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=5
loop_interval=5
