[telegram]
# Get your API ID/HASH from https://my.telegram.org/auth

phone_number="+1 2292810276"
api_id=28286448
api_hash="033df58e2ec65b4352baa6d00f0ac56c"

[sending]
# The send interval is how long you want to wait between sending messages.
# The loop interval is how long you want to wait before re-sending messages to all the groups.

send_interval=0
loop_interval=120
